server:
  port: 443
  ssl:
    key-store: classpath:itech.iskwen.com.jks
    key-store-password: qq19971102
    key-store-type: JKS

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    resources:
      cache-period: 604800
      chain:
        gzipped: true
        cache: false

http:
  port: 80